INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (5.99, 'Pomodori pelati, spolverata di formaggio grattugiato e fior di latte di Agerola ', 'Margherita', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/dzkieoorh0hh2ktj8ob5', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (6.99, 'Pomodori pelati, datterini rossi confit, alici, olive denocciolate, capperi, origano e aglio ', 'Marinara Strange', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/gkqt2nhoeejvalrdjdxo', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (7.99, 'Pomodori pelati, spolverata di formaggio grattugiato e mozzarella di bufala', 'Bufalina', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/w0jq0uuu2pzl4jkory49', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES	(10.99, 'Pomodori pelati, fior di latte di Agerola e alici', 'Napoli', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/rhi77c98l26rxamk4mju', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (11.99, 'Pomodori pelati, fior di latte di Agerola, ventricina piccante', 'Molise', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/snei5hmtaen0dhgb2ys1', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (12.99, 'Fior di latte di Agerola, crema di zucchine, fiori di zucca, zucchine e scaglie di Grana Padano', 'Campania', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/fjiake4gk1acc5n9bm3s', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (13.99, 'Fior di latte di Agerola, datterini gialli e rossi confit e pesto di basilico', 'Liguria', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/bbg7nyf6qisnukgm9coq', '2023-06-22 12:14';
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (13.99, 'Fior di latte di Agerola, mortadella e granella di pistacchio', 'Emilia Romagna', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/vzn1gtd48ntpzv8wtscy', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (13.99, 'Provola affumicata di Agerola, porchetta di Ariccia e cicoria', 'Lazio', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/kjlvqskstut0myibcqj2', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (13.99, 'Pomodori pelati, fior di latte di Agerola, Nduja di Spilinga e caciocavallo', 'Calabria', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/xeh8ipghn4utat2vrg1u', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (13.99, 'Fior di latte di Agerola, bresaola, datterini rossi freschi, rucola e scaglie di Grana Padano', 'Lombardia', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/o3feehuan9tuq7kizzi3', '2023-06-22 12:14');
INSERT INTO `pizzas` (price, description, name, url_pic, created_at) VALUES (13.99, 'Fior di latte di Agerola, speck, ricotta di bufala e fiori di zucca', 'Trentino', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/mqg2xcbdupwnuhiw7a5l', '2023-06-22 12:14');
INSERT INTO `ingredients` (name) VALUES('banana');
INSERT INTO `ingredients` (name) VALUES('ananas');
INSERT INTO `ingredients` (name) VALUES('pesche sciroppate');




<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (5.99, 'Pomodori pelati, spolverata di formaggio grattugiato e fior di latte di Agerola ', 'Margherita', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/dzkieoorh0hh2ktj8ob5', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (6.99, 'Pomodori pelati, datterini rossi confit, alici, olive denocciolate, capperi, origano e aglio ', 'Marinara Strange', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/gkqt2nhoeejvalrdjdxo', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (7.99, 'Pomodori pelati, spolverata di formaggio grattugiato e mozzarella di bufala', 'Bufalina', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/w0jq0uuu2pzl4jkory49', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES	(10.99, 'Pomodori pelati, fior di latte di Agerola e alici', 'Napoli', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/rhi77c98l26rxamk4mju', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (11.99, 'Pomodori pelati, fior di latte di Agerola, ventricina piccante', 'Molise', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/snei5hmtaen0dhgb2ys1', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (12.99, 'Fior di latte di Agerola, crema di zucchine, fiori di zucca, zucchine e scaglie di Grana Padano', 'Campania', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/fjiake4gk1acc5n9bm3s', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (13.99, 'Fior di latte di Agerola, datterini gialli e rossi confit e pesto di basilico', 'Liguria', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/bbg7nyf6qisnukgm9coq', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (13.99, 'Fior di latte di Agerola, mortadella e granella di pistacchio', 'Emilia Romagna', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/vzn1gtd48ntpzv8wtscy', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (13.99, 'Provola affumicata di Agerola, porchetta di Ariccia e cicoria', 'Lazio', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/kjlvqskstut0myibcqj2', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (13.99, 'Pomodori pelati, fior di latte di Agerola, Nduja di Spilinga e caciocavallo', 'Calabria', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/xeh8ipghn4utat2vrg1u', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (13.99, 'Fior di latte di Agerola, bresaola, datterini rossi freschi, rucola e scaglie di Grana Padano', 'Lombardia', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/o3feehuan9tuq7kizzi3', '2023-06-22 12:14', false);
<!--INSERT INTO `pizzas` (price, description, name, url_pic, created_at, deleted) VALUES (13.99, 'Fior di latte di Agerola, speck, ricotta di bufala e fiori di zucca', 'Trentino', 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto:low/Products/mqg2xcbdupwnuhiw7a5l', '2023-06-22 12:14', false);